config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @flats = Flat.where("name LIKE '%#{@name}%'")
    end
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flat.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= flat.description %>
  </p>

  <p>
    <strong>Price per night:</strong>
    <%= flat.price_per_night %>
  </p>

  <p>
    <strong>Number of guests:</strong>
    <%= flat.number_of_guests %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our flats (<%= @flats.count %>)</h1>
    </div>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
        <div class="col-md-4">
          <div class="flat-card">
            <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
            <div class="flat-card-content">
              <div class="flat-card-title">
                <h4><%= flat.name %></h4>
              </div>
              <p><%= flat.address %></p>
              <div class="flex">
                <div class="flex align-items-center">
                  <i class="fa-solid fa-people-line"></i>
                  <span><%= flat.number_of_guests %></span>
                </div>
                <div class="flex align-items-center ms-3">
                  <i class="fa-solid fa-euro-sign"></i>
                  <span><%= flat.price_per_night %></span>
                </div>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to "More info", flat_path(flat) %>
              <%= link_to "Edit", edit_flat_path(flat), class: "ms-3 text-warning" %>
              <%= link_to "Remove", flat_path(flat), class: "ms-3 text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <%= @flat.number_of_guests %> people
          </div>
          <div class="flex ms-3">
            <%= @flat.price_per_night %> €
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa-brands fa-facebook-square me-2"></i>
            <i class="fa-brands fa-twitter-square me-2"></i>
            <i class="fa-brands fa-pinterest-square me-2"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700&family=Karla:wght@400;700;800&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <%= link_to "Simple Airbnb", flats_path, class: "navbar-brand"%>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="ms-auto flex">
                <%= simple_form_for :search, url: flats_path, method: "GET", html: { class: "flex my-2 my-lg-0" } do |f| %>
                  <%= f.input :name, input_html: {value: "", class: "form-control me-2" } %>
                  <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
                <% end %>
              <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2"%>
            </div>
          </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>